### ISSUE TITLE
undefined method `gsub' for nil:NilClass - Firefox on Mac

### ISSUE THREAD

**Issue by dcraig-sage** [Sage/device_wizard#7]
Steps to reproduce:

1. gem install device_wizard
2. irb
3. require 'device_wizard'
4. ua = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:71.0) Gecko/20100101 Firefox/71.0"
5. detector = DeviceWizard::UserAgentDetector.new
6. detector.get_details(ua)

```
NoMethodError: undefined method `gsub' for nil:NilClass
        from /Users/david.craig/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/device_wizard-1.0.0/lib/device_wizard/resolvers/mac.rb:12:in `get_version'
        from /Users/david.craig/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/device_wizard-1.0.0/lib/device_wizard/resolvers/base.rb:19:in `identify'
        from /Users/david.craig/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/device_wizard-1.0.0/lib/device_wizard/user_agent_detector.rb:67:in `block in get_os'
        from /Users/david.craig/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/device_wizard-1.0.0/lib/device_wizard/user_agent_detector.rb:66:in `each'
        from /Users/david.craig/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/device_wizard-1.0.0/lib/device_wizard/user_agent_detector.rb:66:in `get_os'
        from /Users/david.craig/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/device_wizard-1.0.0/lib/device_wizard/user_agent_detector.rb:78:in `get_details'
        from (irb):4
        from /Users/david.craig/.rbenv/versions/2.4.4/bin/irb:11:in `<main>'
irb(main):005:0> require 'pry'
```

**Comment by dcraig-sage** [comment]
Chrome UA
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36`

Firefox UA
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:71.0) Gecko/20100101 Firefox/71.0`

I believe issue is this line: 
https://github.com/Sage/device_wizard/blob/afb83d6251e93a34bee76869cd320110d3eaf1db/lib/device_wizard/resolvers/mac.rb#L8 is assuming the version will have _'s in wheras firefox has .'s

which in turn makes this line:
https://github.com/Sage/device_wizard/blob/afb83d6251e93a34bee76869cd320110d3eaf1db/lib/device_wizard/resolvers/base.rb#L9

return nil

**Comment by chrisbarber86** [comment]
Fixed in https://github.com/Sage/device_wizard/pull/8
